name: webview_dynamic_url
description: WebView Flutter app qui charge dynamiquement l'URL du site depuis un fichier de config distant.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.7.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  flutter_icons:
  android: true
  ios: false
  image_path: "assets/logo.png"
